// Generated by https://quicktype.io

export interface MoviesType {
    id: number;
    type: MoviesTypeType;
    title: string;
    description: string;
    year: number;
    imdb: number;
    comment: boolean;
    rating: number;
    duration: string;
    downloadas: null | string;
    playas: null | string;
    classification: null | string;
    image: string;
    cover: string;
    genres: Genre[];
    sources: Source[];
    country: Country[];
}

export interface Country {
    id: number;
    title: string;
    image: string;
}

export interface Genre {
    id: number;
    title: string;
}

export interface Source {
    id: number;
    quality: string;
    type: SourceType;
    url: string;
}

export enum SourceType {
    Mkv = "mkv",
}

export enum MoviesTypeType {
    Movie = "movie",
    Serie = "serie",
}
